### PR TITLE
style: Enhance coding style with consistency for main.cpp

### PR DESCRIPTION
**Pull request by hcsun**
The original code in `main.cpp` showed inconsistency.
I followed [Google C++ Style Guide](https://google.github.io/styleguide/cppguide.html) and fixed it.
Please advise.

### CODE REVIEW

**Comment by smurthas** [comment]
+1! The mess in `main.cpp` was frustrating to deal with during this project (I had to make changes to it for debugging).

Also, the diff for this PR is easier read if you add `?w=1` to the url, e.g. https://github.com/udacity/CarND-Kidnapped-Vehicle-Project/pull/28/files?w=1

**Comment by Daniel-Prado** [comment]
Please review and approve this pull request.  The main.cpp in this project has been a mesh for 4 months (specially with indentation), I guess since major changes were made to introduce the simulator.

**Comment by wy193777** [comment]
Still a mess..... Have to substitute all tabs to spaces.

**Comment by mvirgo** [comment]
Thanks for these changes! We're going in and trying to refactor a lot of our C++ code to improve style and readability, so there are some further changes we'll make here soon as well, but this gets us part of the way there.

**Pull request merged**
